### PR TITLE
Add possibility to use a custom program to play sound files.

### LINKED ISSUE #13: Use custom commands to play audio files
Hello,

It would be nice if we could manually set the command (`afplay`, `aplay`) for systems that don't have those installed. Or maybe someone needs/wants to use another command for specific purposes.

For example on my computer I have archlinux (and it's probably true for other linux distributions), I don't have ALSA installed which has the `aplay` command, so this mode doesn't work for me. But I do have `play` which works the same, I would love to be able to change the setting in my config file.

### PR DESCRIPTION
**Pull request by ShadowMitia**
This PR allows for custom programs to be set on systems that don't have "afplay" or "aplay" installed.
This can be set in the user's configuration files manually or through `M-x customize`.

This should close #13.

### CODE REVIEW

**Comment by ShadowMitia** [comment]
Also helps with #16

**Comment by Anton-Latukha** [comment]
In PR you assume that person has PulseAudio.

I have, but some people really, really don't.

`aplay` seems was, and is the standard.

If person has PulseAudio installed => Pulse requires ALSA to be installed.
PulseAudio sets itself as default ALSA device. So there is no sense to limit users to `paplay`, that is Pulse utility only.

If you use `aplay`, you automatically use PulseAudio, if Pulse was installed. If Pulse is not present - it uses default ALSA audio device. And it can be ALSA, PipeWire, of Jack1, Jack2, OSS, NAS or whatever sound routing configured as default ALSA device.

**Comment by ShadowMitia** [comment]
I assume that Pulseaudio is the default on most systems, I could be wrong on that and don't mind changing. 

But the whole point of this PR is to be able to change what plays sound easily for the user, so the default should be something that's common to most systems.

Like I said in the issue, I didn't even have `aplay` installed, but maybe that was just a fluke on my system.

Could you share some documentation that shows how `aplay` automatically chooses the output system? I have few experience in sound systems, and I was adamant `aplay` was ALSA only. I would like to read up more on that.

**Comment by Anton-Latukha** [comment]
AFAIK `aplay` on Arch probably is still provided in `alsa-tools`.

It is debatable argument why `paplay` is on your system and `aplay` is not, while your system both uses PulseAudio and ALSA at the same time.

It can be that `paplay` just got packaged into the `pulse` package, while `alsa` maintainer decided to split it into `alsa-tools`. In that case the, on Arch, the `alsa` maintainer seems more in line with the distribution ideas. Or you have `pulse-tools` installed. It depends on the distribution.

I am really up for good migration from dependency of everything on ALSA. They done a big mistake in the base design (it is forgotten story), that PulseAudio also trying to cover up so hard. But for nearest, foreseen, years everything would still run on ALSA, so targeting it seems logical.

I am not really strongly on left or right here, it can stay also as it is or whatever.

**Comment by zellerin** [comment]
Just curious, why simply replacing `selectric-make-sound` with built-in `play-sound-file` does not work?

**Pull request closed without merging**
