### PR TITLE
Delete sound

### PR DESCRIPTION
**Pull request by codesuki**

### CODE REVIEW

**Comment by codesuki** [comment]
The keymap is now attached to the minor mode. I checked with `describe-key` that the keymap is not used if the minor mode is not used.

**Comment by codesuki** [comment]
My emacs indents the else branch of `(if...` so there are some lines changed. If you dislike that I can change it by hand. I think it's easier to understand. Did you set something specific to disable that? I guess you are using emacs too ;)

**Comment by rbanffy** [comment]
Yes, the indentations are a bit odd. I didn't say anything about them to my Emacs, but it could be something I added.

One question: do we need to restore the previous bindings when we use a mode-map?

**Comment by codesuki** [comment]
If the user disables the mode the mode map will be restored automatically.

**Comment by rbanffy** [comment]
Great! Just fix that odd indentation issue and we're good to merge.

**Comment by codesuki** [comment]
Sorry I totally forgot to push here :(

**Comment by rbanffy** [comment]
NP. Thanks for the patch.

**Pull request merged**
