### PR TITLE
Add authentic ping.

### PR DESCRIPTION
**Pull request by joeheyming**
I found a random youtube video online which had an actual
demonstration of an IBM selectric keyboard.

I then downloaded audacity and cut out the precise moment when
then ping occurred.  It was a little harsh, so I made the ping a
little dampened.

Enjoy!

### CODE REVIEW

**Comment by rbanffy** [comment]
Sorry for the late response, @joeheyming. Can you check if the video is licensed in a compatible, OK for derived work and non-commercial use, way?

**Comment by joeheyming** [comment]
I think it was this video:
https://www.youtube.com/watch?v=vOIPN70f_-I

**Comment by rbanffy** [comment]
I asked in the Youtube video. Let's hope the original author clarifies whether we can use the video.

**Comment by rbanffy** [comment]
We are go for merge.

image

**Comment by rbanffy** [comment]
Thank you, @joeheyming.

**Comment by OrionRandD** [comment]
Thx for the package. Brings me good memories back then...
:+1:

**Pull request merged**
